name: kmc
description: A new Smartpalika project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.4+54

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  charts_flutter: null
  connectivity: null
  cupertino_icons: null
  dio: ^4.0.6
  dio_http_cache: 0.3.0
  draggable_scrollbar: ^0.1.0
  easy_localization: ^3.0.1
  external_path: ^1.0.1
  file_picker: ^4.4.0
  flutter_local_notifications: 8.2.0
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk
  flutter_bloc: ^8.0.1
  flutter_cached_pdfview: 0.4.1
  flutter_downloader: ^1.4.4
  flutter_easyloading: ^3.0.3
  flutter_form_builder: 6.0.1
  flutter_html: ^3.0.0-alpha.2
  # flutter_inappwebview: 5.3.2
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: null
  get: ^4.6.6
  google_maps_flutter: ^2.2.4
  image_picker: ^0.8.6+3
  intl: null
  khalti: ^1.0.2
  localstorage: 4.0.0+1
  material_design_icons_flutter: ^6.0.7096
  nepali_date_picker: ^5.1.0
  nepali_utils: null
  new_version: ^0.3.0
  page_transition: ^2.0.5
  percent_indicator: ^4.2.2
  permission_handler: ^10.2.0
  pusher_client: 
    git: 
      url: https://github.com/thijskuilman/pusher_client.git
      ref: master
  reactive_forms: ^10.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  simple_animations: null
  syncfusion_flutter_charts: ^20.4.51
  syncfusion_flutter_pdfviewer: 
  toggle_switch: ^2.0.1
  # webview_flutter: null
  photo_view: ^0.14.0
  double_back_to_close: ^2.0.0
  flutter_inappwebview: ^5.7.1+2
  badges: ^3.0.2
  notification_permissions: ^0.6.1
  path_provider: ^2.0.11
  lecle_downloads_path_provider: ^0.0.2+8
  smooth_page_indicator: ^1.0.0+2
  youtube_player_flutter: ^8.1.1
  equatable: ^2.0.5
  in_app_update: ^4.0.1
  image_cropper: ^3.0.1
  ime_pay:
  map_launcher: ^2.5.0
  geolocator: ^9.0.2
  url_launcher: ^6.2.5
  flutter_file_dialog: ^3.0.2
  firebase_analytics: ^10.10.2



dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.''
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/provinces/
    - assets/images/Banner.png
    - assets/images/header.png
    - assets/images/icons/
    - assets/images/onboarding/
    - assets/images/icons/newIcons/
    - assets/images/icons/sp-icon/
    # - assets/pin.png
    - assets/image.png
    # - assets/pdf.jpg
    - assets/botu.gif
    - assets/json/sifarish/
    - assets/json/login/
    - assets/json/address.json

    # - assets/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta/Mukta-Regular.ttf
          # - asset: assets/fonts/Schyler-Italic.ttf
          # style: italic,
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
